### ISSUE TITLE
Unable to easily access properties on `getNftMetadata`response

### ISSUE THREAD

**Issue by JackCurrie** [alchemyplatform/alchemy-web3#101]
**Code**
```typescript
  const { alchemy } = createAlchemyWeb3(ALCHEMY_URL);

  const test = { contractAddress: "0x6688Ee4E6e17a9cF88A13Da833b011E64C2B4203", tokenId: "1" };
  const nft = await alchemy.getNftMetadata(test);
  console.dir(nft);
```

**Response**
<img width="1265" alt="Screen Shot 2022-02-23 at 10 16 16 PM" src="https://user-images.githubusercontent.com/15962247/155468836-751d5928-aa88-46ca-a586-310f1149669e.png">

**Description of Problem**
while fetching an NFT, I am trying to access a few properties inside the `metadata` property on the response such as `external_url` and `animation_url`. I realize that these are not standard necessarily (though common), so I cannot expect to receive these as responses all the time.

This interface is currently described by the following interface: 
https://github.com/alchemyplatform/alchemy-web3/blob/5d3985f627fb72502b3b124613a2d3631ad19b3b/src/alchemy-apis/types.ts#L81-L86

As a user I would expect that these non-standard properties would either be listed as optional types on this interface, or to just be jammed into `attributes` record (or else some "optional_properties" record of some sort if the `attributes` actually usually holds other more standardized data.

**Comment by thebrianchen** [comment]
@JackCurrie Thanks for filing a well thought-out FR!

I'm currently tackling is part of resolving #99 in the PR: #100. I'm planning on adding the few most common ones like `name` and `description`. I'm extending changing `NftMetadata` to `NftMetadata extends Record<string, any>`, which should allow you to access any attributes not listed.

**Comment by JackCurrie** [comment]
Awesome, thank you @thebrianchen , appreciate the quick response! 👍
