### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by ishancs** [alchemyplatform/alchemy-web3#105]
import {pinJSONToIPFS} from './pinata.js'
require('dotenv').config();
const alchemyKey = process.env.ALCHEMY_KEY;
const { createAlchemyWeb3 } = require("@alch/alchemy-web3");
const web3 = createAlchemyWeb3(alchemyKey);
const contractABI = require('../contract-abi.json')
const contractAddress = process.env.CONTRACT_ADDRESS;

export const mintNFTWeb3 = async (url, name, description) => {
  //error handling
 if (url.trim() == "" || (name.trim() == "" || description.trim() == "")) { 
  return {
   success: false,
   status: "❗Please make sure all fields are completed before minting.",
  }
 }
 //make metadata
 const metadata = new Object();
 metadata.name = name;
 metadata.image = url;
 metadata.description = description;

 //make pinata call
 const pinataResponse = await pinJSONToIPFS(metadata);
 if (!pinataResponse.success) {
     return {
         success: false,
         status: "😢 Something went wrong while uploading your tokenURI.",
     }
 } 
 const tokenURI = pinataResponse.pinataUrl;
 // window.contract = await new web3.eth.Contract(contractABI, contractAddress);

 //set up your Ethereum transaction
  const transactionParameters = {
    to: contractAddress, // Required except during contract publications.
    from: window.ethereum.selectedAddress, // must match user's active address.
    'data': window.contract.methods.mintNFT(window.ethereum.selectedAddress, tokenURI).encodeABI()//make call to NFT smart contract 
  };

  //sign the transaction via Metamask
  try {
    const txHash = await window.ethereum
      .request({
          method: 'eth_sendTransaction',
          params: [transactionParameters],
      });
    return {
      success: true,
      status: "✅ Check out your transaction on Etherscan: https://ropsten.etherscan.io/tx/" + txHash
    }
  } catch (error) {
    return {
      success: false,
      status: "😥 Something went wrong: " + error.message
    }
  }

}

**Comment by ishro-app** [comment]
It was issue with undefined value from const alchemyApiUrl = process.env.ALCHEMY_API_URL;

**Comment by ishancs** [comment]
It was issue with undefined value from const alchemyApiUrl = process.env.ALCHEMY_API_URL;
