### ISSUE TITLE
TypeScript error when using DEFAULT_TOKENS with getTokenBalances

### ISSUE THREAD

**Issue by psawaya** [alchemyplatform/alchemy-web3#109]
Your [docs](https://docs.alchemy.com/alchemy/enhanced-apis/token-api#alchemy_gettokenbalances) say valid values for the second parameter are:
> One of:
> Array - A list of contract addresses
> The String"DEFAULT_TOKENS" - denotes a query for the top 100 tokens by 24 hour volume

However, I get 
> error TS2345: Argument of type 'string' is not assignable to parameter of type 'string[]'.

when I call

>  const balances = await web3.alchemy.getTokenBalances(
      'foo',
      'DEFAULT_TOKENS',
    );

**Comment by thebrianchen** [comment]
@psawaya Our package implements it a little differently. If you omit the `contractAddresses` parameter, it will populate `DEFAULT_TOKENS` automatically. See the [documentation](https://github.com/alchemyplatform/alchemy-web3#web3alchemygettokenbalancesaddress-contractaddresses)

Marking this issue as closed but feel free to ask any other questions you may have!
