### ISSUE TITLE
web3.eth.getMaxPriorityFeePerGas is not a function

### ISSUE THREAD

**Issue by PavlosIsaris** [alchemyplatform/alchemy-web3#115]
I am using version `1.3.0` of the library, and I am trying the following:

```bash
web3.eth.getMaxPriorityFeePerGas().then(console.log);
```
But there is no `getMaxPriorityFeePerGas` method defined. Am I doing something wrong?

**Comment by thebrianchen** [comment]
@PavlosIsaris I'm able to do run the following snippet on `1.3.0`.

```js
import {
    createAlchemyWeb3
} from "@alch/alchemy-web3";

const alch = createAlchemyWeb3('https://eth-mainnet.alchemyapi.io/v2/demo');
alch.eth.getMaxPriorityFeePerGas().then(console.log);
```

The resulting output from my run was: `0x3b9aca00`. If you continue to have issues, please post a repro, thanks!

**Comment by PavlosIsaris** [comment]
@thebrianchen thanks, it works!
