### ISSUE TITLE
Usage in React

### ISSUE THREAD

**Issue by sblackstone** [alchemyplatform/alchemy-web3#126]
Using this inside React (react scripts v4.0.3) I'm getting the following error occuring, not always on page load but somewhat randomly.  

```
VM6639:2 Uncaught ReferenceError: process is not defined
    at Object.4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at Object.8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at Object.8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at HTMLIFrameElement.e.onload (index.js:1:1)
```

I'm unsure exactly what is causing this, but it appears to be from the underlying `web3.js` having dependencies from node and hence on process.

Do you have any suggestions?  Am I doing something wrong here?

**Comment by thebrianchen** [comment]
You will need to process, since React doesn't bundle them anymore. See this Stackoverflow [link](https://stackoverflow.com/questions/64557638/how-to-polyfill-node-core-modules-in-webpack-5) for more details.

Closing the issue since this is not a problem with alchemy-web3.
