### ISSUE TITLE
AlchemyWeb3.eth.subcribe("logs", { topics: [] }) does not filter on topic array length like the composer

### ISSUE THREAD

**Issue by KjetilVaa** [alchemyplatform/alchemy-web3#128]
Version: 1.2.2

Using this topic filter: https://composer.alchemyapi.io?share=eJxti70KgzAURl_l3NlBExOjY_fSsUuUcvOnUmNEU1oQ372hQ6cOHxw_ztlBDzjO0OQZzDa_wvr4srdxCOaK3kIDie_9jZfQb5DBgiv6G05Pu0Ejd3Br8Ocp6BTChNFuMUkx.LmWUacEpGwhfxvjCCNoCmWJFrXitSYq58JpWgmDWDOisHIFp7rEouBEOMawNI4Rqqh1LXTZSf7WwdEdH05iQOM-

All logs returned should have a topic length of 4 (as specifiec by the query.). The Alchemy composer does this
but AlchemyWeb3.eth.subscribe("logs", topics: [["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"], [], [], []]) does not.

**Comment by KjetilVaa** [comment]
Example response the I get from AlchemyWeb3.eth.subscribe but not from the compose:

`{
  "address": "0xFc0d6Cf33e38bcE7CA7D89c0E292274031b7157A",
  "topics": [
    "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
    "0x0000000000000000000000009b7fa79317a864c54b0bdf852a932613f8540f3f",
    "0x000000000000000000000000d1df645e3e15fb252e7dbd39e2bf6851d8f93f72"
  ],
  "data": "0x000000000000000000000000000000000000000000000061784331c9a8580000",
  "blockNumber": 14723707,
  "transactionHash": "0x483827cf7150e33140417ada4765fe04b74559c0e84fb281efa6d067f1c81841",
  "transactionIndex": 79,
  "blockHash": "0x10cbd6cddd85b8098c1fa0ce4f29a8c74a32f60a4834eab5a0f31c7d0489e276",
  "logIndex": 56,
  "removed": false,
  "id": "log_d6a50d8e"
}

{
  "address": "0x903bEF1736CDdf2A537176cf3C64579C3867A881",
  "topics": [
    "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
    "0x000000000000000000000000e66b31678d6c16e9ebf358268a790b763c133750",
    "0x00000000000000000000000055f2a327d13d960e6aec345073f999bd00d4621c"
  ],
  "data": "0x0000000000000000000000000000000000000000000000000000002e33d61f0e",
  "blockNumber": 14723707,
  "transactionHash": "0x3290a02b5c0d08f38e30c47def1cde25f2f11f997449571791d27cd5efc91a92",
  "transactionIndex": 75,
  "blockHash": "0x10cbd6cddd85b8098c1fa0ce4f29a8c74a32f60a4834eab5a0f31c7d0489e276",
  "logIndex": 48,
  "removed": false,
  "id": "log_1542d1a6"
}`

Notice the topics.length here.

**Comment by thebrianchen** [comment]
@KjetilVaa Thanks for flagging this issue! The Alchemy Composer has the correct behavior. Geth nodes return logs with topic array length greater than or equal to the number of topics in the filter. This was a bug in our internal websocket implementation and has now been fixed to match the Geth node behavior thanks to @dphilipson.
