### ISSUE TITLE
FR: Support NFT metadata refreshes

### ISSUE THREAD

**Issue by dminglv** [alchemyplatform/alchemy-web3#129]
Hello! I burned the token, but for some reason AlchemyAPI returns it anyway.

Network: **Polygon Mumbai**
API request: **getNFTs**

```
{
    "ownedNfts": [
        {
            "contract": {
                "address": "0x356881528562ab0f269a5d1982fd21b83fb835b0"
            },
            "id": {
                "tokenId": "86",
                "tokenMetadata": {
                    "tokenType": "ERC721"
                }
            },
            "title": "",
            "description": "",
            "tokenUri": {
                "raw": "Unable to get token URI",
                "gateway": ""
            },
            "media": [
                {
                    "raw": "",
                    "gateway": ""
                }
            ],
            "metadata": {},
            "timeLastUpdated": "2022-05-06T10:47:18.835Z",
            "error": "Token does not exist"
        }
    ],
    "totalCount": 1,
    "blockHash": "0xb15dfe1fb416408406ea54946b6339a17b04f1725934e80e6c4137de964ff06e"
}
```

**Comment by thebrianchen** [comment]
@dminglv Thanks for writing in! The NFT API does immediately process metadata changes since we have no way of knowing when the underlying metadata URL on the NFT changes. Alchemy will periodically check for metadata updates, and we're currently working on a feature to allow users to manually refresh their NFT metadata. Stay tuned!

**Comment by thebrianchen** [comment]
@dminglv We're working on improving our metadata refresh rate, but If you find a particular NFT's metadata is stale, you can refresh the NFT metadata manually. It's currently a feature on our new [beta SDK](https://www.alchemy.com/alchemy/enhanced-apis/nft-api/reingestcontract) as `refreshNftMetadata()`.
