### ISSUE TITLE
Subscription api inconsistent with document

### ISSUE THREAD

**Issue by wong2** [alchemyplatform/alchemy-web3#138]
The document https://docs.alchemy.com/alchemy/enhanced-apis/subscription-api-websockets#alchemy_pendingtransactions and typings of this SDK are not consistent in method name and args, I'm not sure which one should I trust.

**Comment by thebrianchen** [comment]
@wong2 Thanks for filing the issue. We're currently on the next version of the SDK at https://www.npmjs.com/package/@alch/alchemy-sdk. The Subscription API was recently updated with the new params, and I'll have a PR out shortly to reflect these new changes.
