### ISSUE TITLE
Getting too many net_version requests on Alchemy Node

### ISSUE THREAD

**Issue by GarvMaggu** [alchemyplatform/alchemy-web3#141]
This is my alchemy account, I'm using createAlchemyWeb3 method for a socket connection to an Alchemy Node.
I'm not sending any "net_version" requests but it's consuming around 1 million compute units every day. 
How can I prevent the module to avoid sending these many net_version requests?

![image](https://user-images.githubusercontent.com/17963209/177857567-2cc9f1cb-8ad0-40a7-853a-147c9a9ea3cb.png)
![image](https://user-images.githubusercontent.com/17963209/177857941-97356d55-9c5b-4a4f-be49-b146fbf46dab.png)

**Comment by thebrianchen** [comment]
Hey @GarvMaggu! This is unexpected since we shouldn't charge for `net_version`. Can you share your app team/id with support@alchemy.com? Thanks!

**Comment by GarvMaggu** [comment]
Hi @thebrianchen! Yes, I'm not getting charged for `net_version` requests on Alchemy, but I'm also using a few other node providers and some of them are charging for it.

Not an issue though, I switched to HTTPS provider at a few places, and now `net_version` requests are not too much.

Thank you for the info!
