### ISSUE TITLE
Error when getting transaction history

### ISSUE THREAD

**Issue by viktor111** [alchemyplatform/alchemy-web3#144]
Im trying to get transaction history for address to work but get this error.

```
Error: Invalid category param: category must be a non-empty list containing the possible values: {external, internal, token, erc20, erc721, erc1155, specialnft}
```

code:

``` typescript
async getTransactionsAlchemy(address: string) {
        const alchemyWeb3 = createAlchemyWeb3(EthereumConstants.ALCHEMY_GOERLI_PROVIDER_URL);
        const transactions = await alchemyWeb3.alchemy.getAssetTransfers({ fromBlock: "0x0", fromAddress: address, });
        return transactions;
    }
```

**Comment by thebrianchen** [comment]
@viktor111 Thanks for catching this! You'll need to also specify a `category` field, as of the new [changelog entry](https://docs.alchemy.com/alchemy/documentation/changelog#06-27-2022) from June 27. I'll submit an update to reflect this change in this library as well.
