### ISSUE TITLE
Hex to Decimal function is broken

### ISSUE THREAD

**Issue by johnrjj** [alchemyplatform/alchemy-web3#19]
https://github.com/alchemyplatform/alchemy-web3/blob/master/src/index.ts#L237-L260 incorrectly converts hex values to decimals in some cases.

Please consider using web3-util's version instead, as it is already installed and quite robust.

Given the valid hex value `0x0000000000000000000000000000000000000000000000004563918244f40072` (i.e. 5 DAI) the function will incorrectly convert it to `500` instead of `5000000000000000114`

Codesandbox repro along with a proposed fix: https://codesandbox.io/s/infallible-cache-kmomc

**Comment by dphilipson** [comment]
Thank you so much for the report! This fix is published in version 1.1.13.
