### ISSUE TITLE
Not supported method eth_getBlockByNumber

### ISSUE THREAD

**Issue by mila1808** [alchemyplatform/alchemy-web3#28]
I've initiated the Alchemy web (version: `"@alch/alchemy-web3": "^0.1.18"`) as follows

```
import { createAlchemyWeb3 } from '@alch/alchemy-web3'

web3 = createAlchemyWeb3('https://eth-mainnet.alchemyapi.io/v2/my-key')

```
But, I get the following error
```

Request
{"jsonrpc":"2.0","id":75,"method":"eth_getBlockByNumber","params":[null,false]}

Response
{"jsonrpc": "2.0", "id": 75, "error": {"code": -32602, "message": "Invalid method parameter(s)."}}
```

**Comment by dphilipson** [comment]
Hi @mila1808,

What call are you making which triggers that request?

**Comment by mila1808** [comment]
@dphilipson 
`getTransactionReceipt`

**Comment by mila1808** [comment]
> Hi @mila1808,
> 
> What call are you making which triggers that request?

`getTransactionReceipt`

**Comment by dphilipson** [comment]
Would you be able to post sample code which triggers this bug? I haven't been able to reproduce. What I tried:

```js
import { createAlchemyWeb3 } from '@alch/alchemy-web3'

const web3 = createAlchemyWeb3('https://eth-mainnet.alchemyapi.io/v2/my-key')
web3.eth.getTransactionReceipt('0x4066c7cd32b00d0b2706eecbaae540be24b02174cb3c3198d1e87eeecdc5c567')
  .then(console.log)
```
which prints as expected:
```
{transactionHash: "0x4066c7cd32b00d0b2706eecbaae540be24b02174cb3c3198d1e87eeecdc5c567", blockHash: "0x3059421a89cb411882900ce57f00aa3cb872bd66d7404fc1e66cc56958312eb5", blockNumber: 11450385, contractAddress: null, cumulativeGasUsed: 21000, …}
```

**Comment by mila1808** [comment]
> Would you be able to post sample code which triggers this bug? I haven't been able to reproduce. What I tried:
> 
> ```js
> import { createAlchemyWeb3 } from '@alch/alchemy-web3'
> 
> const web3 = createAlchemyWeb3('https://eth-mainnet.alchemyapi.io/v2/my-key')
> web3.eth.getTransactionReceipt('0x4066c7cd32b00d0b2706eecbaae540be24b02174cb3c3198d1e87eeecdc5c567')
>   .then(console.log)
> ```
> 
> which prints as expected:
> 
> ```
> {transactionHash: "0x4066c7cd32b00d0b2706eecbaae540be24b02174cb3c3198d1e87eeecdc5c567", blockHash: "0x3059421a89cb411882900ce57f00aa3cb872bd66d7404fc1e66cc56958312eb5", blockNumber: 11450385, contractAddress: null, cumulativeGasUsed: 21000, …}
> ```

Actually, my current code invokes a 3rd party smart contract. I'm not very sure the exact method that results in the call of `getTransactionReceipt`. 
But apparently that, the method `eth_getBlockByNumber` provided by Alchemy web3 has some issue?

**Comment by dphilipson** [comment]
Can you clarify how `getTransactionReceipt` is involved then? How do you become aware that it's involved?

**Comment by mila1808** [comment]
> Can you clarify how `getTransactionReceipt` is involved then? How do you become aware that it's involved?


I get the following error when switching to Alchemy web3. This error doesn't happen when using Metamask provider
I don't remember exactly which triggers the call of the method `eth_getBlockByNumber`
Could you try calling the method `eth_getBlockByNumber`? See if same error or not?

```

Request
{"jsonrpc":"2.0","id":75,"method":"eth_getBlockByNumber","params":[null,false]}

Response
{"jsonrpc": "2.0", "id": 75, "error": {"code": -32602, "message": "Invalid method parameter(s)."}}
```

**Comment by dphilipson** [comment]
Sure. Trying this:
```js
import { createAlchemyWeb3 } from '@alch/alchemy-web3'

const web3 = createAlchemyWeb3('https://eth-mainnet.alchemyapi.io/v2/my-key')
web3.eth.getBlock(11450383).then(console.log)
```
prints the expected
```
{number: 11450383, difficulty: "3562193403046612", extraData: "0x7070796520e4b883e5bda9e7a59ee4bb99e9b1bc010c", gasLimit: 12512030, gasUsed: 12480345, …}
```
while making the request
```
{"method":"eth_getBlockByNumber","params":["0xaeb80f",false],"jsonrpc":"2.0","id":4}
```

**Comment by mila1808** [comment]
> Sure. Trying this:
> 
> ```js
> import { createAlchemyWeb3 } from '@alch/alchemy-web3'
> 
> const web3 = createAlchemyWeb3('https://eth-mainnet.alchemyapi.io/v2/my-key')
> web3.eth.getBlock(11450383).then(console.log)
> ```
> 
> prints the expected
> 
> ```
> {number: 11450383, difficulty: "3562193403046612", extraData: "0x7070796520e4b883e5bda9e7a59ee4bb99e9b1bc010c", gasLimit: 12512030, gasUsed: 12480345, …}
> ```
> 
> while making the request
> 
> ```
> {"method":"eth_getBlockByNumber","params":["0xaeb80f",false],"jsonrpc":"2.0","id":4}
> ```

Thanks for your trying.
Now, I can see the difference. 

Yours
`{"method":"eth_getBlockByNumber","params":["0xaeb80f",false],"jsonrpc":"2.0","id":4}`

Mine
`{"jsonrpc":"2.0","id":75,"method":"eth_getBlockByNumber","params":[null,false]}`

Then, by whatever reason, the method `eth_getBlockByNumber` is invoked with `null` block number as input param. 
Then, it is not Alchemy problem. I'll close this issue
