### ISSUE TITLE
Metamask warning "MetaMask no longer injects web3"

### ISSUE THREAD

**Issue by mila1808** [alchemyplatform/alchemy-web3#32]
1. Environment

Web browser with Metamask version `9.0.3`

2. Problem

The method `createAlchemyWeb3` is now causing the Metamask warning `MetaMask no longer injects web3`
Pls see this screenshot

![Screenshot from 2021-01-27 19-20-06](https://user-images.githubusercontent.com/62562267/105990214-c20e9180-60d4-11eb-9056-cff64a0e55e8.png)

**Comment by sambacha** [comment]
Are you using the websocket connection?

**Comment by dphilipson** [comment]
This should be fixed in version 1.0.0. Please let me know if the problem persists.
