### ISSUE TITLE
web3.eth.personal.ecRecover calls alchemy & returns uncaught Error 400 undefined

### ISSUE THREAD

**Issue by goodspeed3** [alchemyplatform/alchemy-web3#62]
I'm trying to sign a message and recover it using web3.  The wrapper seems to make a network call, which arguably shouldn't happen with ecRecover.

To reproduce, use this code:

```
var signedData = await web3.eth.personal.sign(msg, walletAddress, "")

const recovered = await web3.eth.personal.ecRecover(msg, signedData)
console.log(recovered)
```

![image](https://user-images.githubusercontent.com/5751035/133945378-69e0e1b0-64b1-4a0a-aba0-101ec7109a02.png)

Oh, and not using the Alchemy Web3 wrapper works perfectly.

**Comment by thebrianchen** [comment]
@goodspeed3 Apologies for the delay in getting back to you, but I was able to reproduce this. Will investigate and update the issue accordingly.
