### ISSUE TITLE
Dist Folder Missing

### ISSUE THREAD

**Issue by woodydeck** [alchemyplatform/alchemy-web3#68]
This repo comes in typescript without comments, and without any sort of idea what is going on under the hood. I don't know where to find the unminified build so I can take out all the bloat in Web3 I don't need. The minified file is a whopping 1.4MB. It's far too big for something that just needs basic contract calls, and goes out over mobile.

**Comment by thebrianchen** [comment]
@woodydeck We're currently exporting both the minified and non-minified files. Under `/dist` you'll find both `alchemyWeb3.js` and `alchemyWeb3.min.js`. This was added in November 2021.

Marking the issue as closed but feel free to follow up with any other questions!
