### ISSUE TITLE
alchemyapi.io vs alchemy.com

### ISSUE THREAD

**Issue by dlazares** [alchemyplatform/alchemy-web3#91]
Running into `Error: Alchemy specific rest endpoints are not available with our legacy endpoints on alchemyapi.io, please switch over to alchemy.com` on version 1.2.1. When I switch the URL, I get `FetchError: request to https://eth-mainnet.alchemy.com/REMOVED_PII_API_KEY_FOR_GITHUB/v1/getNFTs/?owner=0xeB94Bd011F6b794B6C846457b85Efa895D2DD744 failed, reason: connect ETIMEDOUT 23.45.205.250:443`

This PR seems to also address this issue
https://github.com/alchemyplatform/alchemy-web3/pull/88

**Comment by dphilipson** [comment]
Thank you for the report! The fix is published in version 1.2.3.
