### ISSUE TITLE
Does it support sendTransaction method in React Native?

### ISSUE THREAD

**Issue by fatiherdogan01** [alchemyplatform/alchemy-web3#95]
I am trying to implement `sendTransaction` method in React Native.
I can't connect to crypto wallets.
Should i use a package like `walletConnect`?
Do you have an example of this?

**Comment by thebrianchen** [comment]
@fatiherdogan01 This package is specifically for using Alchemy as a node provider. For a package with wallet support, check out [ethers.js](https://docs.ethers.io/v5/).
