### ISSUE TITLE
web3.alchemy.getTransactionReceipts() doesn't return the same typing as defined in TransactionReceiptsResponse

### ISSUE THREAD

**Issue by RyanWilkins** [alchemyplatform/alchemy-web3#96]
When running `web3.alchemy.getTransactionReceipts()`, you receive a `TransactionReceiptsResponse`, which contains an array of `TransactionReceipt` in the `receipts` key.

These `TransactionReceipt` objects are typed using the web3.js `TransactionReceipt` interface, which defines the following:

```
export interface TransactionReceipt {
    status: boolean;
    transactionHash: string;
    transactionIndex: number;
    blockHash: string;
    blockNumber: number;
    from: string;
    to: string;
    contractAddress?: string;
    cumulativeGasUsed: number;
    gasUsed: number;
    logs: Log[];
    logsBloom: string;
    events?: {
        [eventName: string]: EventLog;
    };
}
```

Looking at one of the actual elements it returns, there are some differences:

```
blockHash:"0x1f302b67a0274bce84ba8c051259073adf3861cda348ebe7d503e88341d12dc4"
blockNumber:"0xd89734"
contractAddress:null
cumulativeGasUsed:"0x22eea"
effectiveGasPrice:"0xdabb435e5"
from:"0xb58555fcba6479fced7de1485eb054943a09af7b"
gasUsed:"0x22eea"
logs:Array(3) [Object, Object, Object]
logsBloom:"0x000..." 
status:"0x1"
to:"0x00000000003b3cc22af3ae1eac0440bcee416b40"
transactionHash:"0x13938092bb6663ad1817a0923c947e1ae951402105d10d6ebb041313aedbd51f"
transactionIndex:"0x0"
type:"0x2"
```

Namely - gasUsed, cumulativeGasUsed, transactionIndex are all (hex) strings. Type does not exist in TransactionReceipt.

I'm getting a bunch of Typescript complaints from this trying to setup my `mongoose` Schemas.

**Comment by thebrianchen** [comment]
@RyanWilkins Thanks for catching this! Will have a fix out for this sometime next week.
