### ISSUE TITLE
withMetadata for getNfts

### ISSUE THREAD

**Issue by elie222** [alchemyplatform/alchemy-web3#99]
The docs have an option to fetch metadata when fetching nfts. This package doesn't support it:

Docs: https://docs.alchemy.com/alchemy/enhanced-apis/nft-api/getnfts#parameters

> withMetadata: (optional) includes metadata for each returned token

Types for this package:

```ts
export interface GetNftsParams {
    owner: string;
    pageKey?: string;
    contractAddresses?: string[];
}
```

**Comment by thebrianchen** [comment]
@elie222 Thanks for flagging this! Will get something out in the coming week or two.

**Comment by JackCurrie** [comment]
@thebrianchen our team is very excited for this feature, thank you!
